<?php

function lst_menu() {
  return [
    'lst' => [
      'menu_name'       => 'main-menu',
      'type'            => MENU_NORMAL_ITEM,
      'title'           => t('LST'),
      'description'     => t('time based on the position of the sun at your location'),
      'page callback'   => 'lst_view',
      'file'            => 'lst.view.inc',
      'access callback' => TRUE,
      'weight'          => 1,
    ],
  ];
}
